### ISSUE TITLE
4k 200%缩放部件太小

### ISSUE THREAD

**Issue by jiqinga** [SteveHsuDrawing/quanto#10]
在4k 200%缩放下感觉好小，能调整大小吗，还有磁盘名称是0可以修改吗，暂时没找到修改的地方
![rain](https://github.com/SteveHsuDrawing/quanto/assets/41818729/6414b49e-83e9-457d-9595-8346edb49693)

**Comment by SteveHsuDrawing** [comment]
1. 可以通过「缩放」功能来放大皮肤外观。请依次打开「全局设置」→「实验室」，找到「缩放」一项，将其设置为「2x」。如果需要更大尺寸，可使用「自定义」，但请务必谨慎设置。

2. 请务必阅读 [Quanto Wiki 中的相关说明「如何配置系统监控软件」](https://github.com/SteveHsuDrawing/quanto/wiki/Troubleshooting#important-how-to-configure-my-system-monitoring-software)。

**Comment by jiqinga** [comment]
谢谢，已经解决
